let data = [
    { city: "Hong Kong", country: " China", primaryLanguage: "" },
    { city: "Bangkok", country: " Thailand", primaryLanguage: "" },
    { city: "London", country: " UK", primaryLanguage: "" },
    { city: "Singapore", country: " Singapore", primaryLanguage: "" },
    { city: "Macau", country: " Macau", primaryLanguage: "" },
    { city: "Dubai", country: " United Arab Emirates", primaryLanguage: "" },
    { city: "Paris", country: " France", primaryLanguage: "" },
    { city: "New York City", country: " USA", primaryLanguage: "" },
    { city: "Shenzhen", country: " China", primaryLanguage: "" },
    { city: "Kuala Lumpur", country: " Malaysia", primaryLanguage: "" },
    { city: "Phuket", country: " Thailand", primaryLanguage: "" },
    { city: "Rome", country: " Italy", primaryLanguage: "" },
    { city: "Tokyo", country: " Japan", primaryLanguage: "" },
    { city: "Taipei", country: " Taiwan", primaryLanguage: "" },
    { city: "Istanbul", country: " Turkey", primaryLanguage: "" },
    { city: "Seoul", country: " South", primaryLanguage: "" },
    { city: "Guangzhou", country: " China", primaryLanguage: "" },
    { city: "Prague", country: " Czech Republic", primaryLanguage: "" },
    { city: "Mecca", country: " Saudi Arabia", primaryLanguage: "" },
    { city: "Miami", country: " USA", primaryLanguage: "" },
    { city: "Delhi", country: " India", primaryLanguage: "" },
    { city: "Mumbai", country: " India", primaryLanguage: "" },
    { city: "Barcelona", country: " Spain", primaryLanguage: "" },
    { city: "Pattaya", country: " Thailand", primaryLanguage: "" },
    { city: "Shanghai", country: " China", primaryLanguage: "" },
    { city: "Las Vegas", country: " USA", primaryLanguage: "" },
    { city: "Milan", country: " Italy", primaryLanguage: "" },
    { city: "Amsterdam", country: " Netherlands", primaryLanguage: "" },
    { city: "Antalya", country: " Turkey", primaryLanguage: "" },
    { city: "Vienna", country: " Austria", primaryLanguage: "" },
    { city: "Los Angeles", country: " USA", primaryLanguage: "" },
    { city: "Cancun", country: " Mexico", primaryLanguage: "" },
    { city: "Osaka", country: " Japan", primaryLanguage: "" },
    { city: "Berlin", country: " Germany", primaryLanguage: "" },
    { city: "Agra", country: " India", primaryLanguage: "" },
    { city: "Ho Chi Minh City", country: " Vietnam", primaryLanguage: "" },
    { city: "Johannesburg", country: " South Africa", primaryLanguage: "" },
    { city: "Venice", country: " Italy", primaryLanguage: "" },
    { city: "Madrid", country: " Spain", primaryLanguage: "" },
    { city: "Orlando", country: " USA", primaryLanguage: "" },
    { city: "Riyadh", country: " Saudi Arabia", primaryLanguage: "" },
    { city: "Johor Bahru", country: " Malaysia", primaryLanguage: "" },
    { city: "Dublin", country: " Ireland", primaryLanguage: "" },
    { city: "Florence", country: " Italy", primaryLanguage: "" },
    { city: "Chennai", country: " India", primaryLanguage: "" },
    { city: "Moscow", country: " Russia", primaryLanguage: "" },
    { city: "Athens", country: " Greece", primaryLanguage: "" },
    { city: "Jaipur", country: " India", primaryLanguage: "" },
    { city: "Beijing", country: " China", primaryLanguage: "" },
    { city: "Denpasar", country: " Indonesia", primaryLanguage: "" },
    { city: "Toronto", country: " Canada", primaryLanguage: "" },
    { city: "Ha Noi", country: " Vietnam", primaryLanguage: "" },
    { city: "Sydney", country: " Australia", primaryLanguage: "" },
    { city: "San Francisco", country: " USA", primaryLanguage: "" },
    { city: "Budapest", country: " Hungary", primaryLanguage: "" },
    { city: "Ha", country: " Long", primaryLanguage: "" },
    { city: "Punta Cana", country: " Dominican Republic", primaryLanguage: "" },
    { city: "Dammam City", country: " Saudi Arabia", primaryLanguage: "" },
    { city: "Munich", country: " Germany", primaryLanguage: "" },
    { city: "Zhuhai", country: " China", primaryLanguage: "" },
    { city: "Lisbon", country: " Portugal", primaryLanguage: "" },
    { city: "Cairo", country: " Egypt", primaryLanguage: "" },
    { city: "Penang Island", country: " Malaysia", primaryLanguage: "" },
    { city: "Doha", country: " Qatar", primaryLanguage: "" },
    { city: "Copenhagen", country: " Denmark", primaryLanguage: "" },
    { city: "Heraklion", country: " Greece", primaryLanguage: "" },
    { city: "Jerusalem", country: " Israel", primaryLanguage: "" },
    { city: "Edirne", country: " Turkey", primaryLanguage: "" },
    { city: "Phnom Penh", country: " Cambodia", primaryLanguage: "" },
    { city: "St Petersburg", country: " Russia", primaryLanguage: "" },
    { city: "Jeju", country: " South Korea", primaryLanguage: "" },
    { city: "Kyoto", country: " Japan", primaryLanguage: "" },
    { city: "Chiang Mai", country: " Thailand", primaryLanguage: "" },
    { city: "Warsaw", country: " Poland", primaryLanguage: "" },
    { city: "Krakow", country: " Poland", primaryLanguage: "" },
    { city: "Honolulu", country: " USA", primaryLanguage: "" },
    { city: "Melbourne", country: " Australia", primaryLanguage: "" },
    { city: "Tel Aviv", country: " Israel", primaryLanguage: "" },
    { city: "Marrakech", country: " Morocco", primaryLanguage: "" },
    { city: "Brussels", country: " Belgium", primaryLanguage: "" },
    { city: "Auckland", country: " New Zealand", primaryLanguage: "" },
    { city: "Vancouver", country: " Canada", primaryLanguage: "" },
    { city: "Jakarta", country: " Indonesia", primaryLanguage: "" },
    { city: "Frankfurt", country: " Germany", primaryLanguage: "" },
    { city: "Artvin", country: " Turkey", primaryLanguage: "" },
    { city: "Guilin", country: " China", primaryLanguage: "" },
    { city: "Stockholm", country: " Sweden", primaryLanguage: "" },
    { city: "Rio de Janeiro", country: " Brazil", primaryLanguage: "" },
    { city: "Kolkata", country: " India", primaryLanguage: "" },
    { city: "Buenos Aires City", country: " Argentina", primaryLanguage: "" },
    { city: "Chiba", country: " Japan", primaryLanguage: "" },
    { city: "Siem Reap", country: " Cambodia", primaryLanguage: "" },
    { city: "Nice", country: " France", primaryLanguage: "" },
    { city: "Mexico City", country: " Mexico", primaryLanguage: "" },
    { city: "Lima", country: " Peru", primaryLanguage: "" },
    { city: "Taichung", country: " Taiwan", primaryLanguage: "" },
    { city: "Rhodes", country: " Greece", primaryLanguage: "" },
    { city: "Washington DC", country: " USA", primaryLanguage: "" },
    { city: "Abu Dhabi", country: " United Arab Emirates", primaryLanguage: "" },
    { city: "Colombo", country: " Sri Lanka", primaryLanguage: "" }
  ];
  
  let languages = [
    "Afrikaans (South Africa)",
    "Amharic (Ethiopia)",
    "Armenian (Armenia)",
    "Azerbaijani (Azerbaijan)",
    "Indonesian (Indonesia)",
    "Malay (Malaysia)",
    "Bengali (Bangladesh)",
    "Bengali (India)",
    "Catalan (Spain)",
    "Czech (Czech Republic)",
    "Danish (Denmark)",
    "German (Germany)",
    "English (United States)",
    "Spanish (Spain)",
    "Basque (Spain)",
    "Filipino (Philippines)",
    "French (France)",
    "Galician (Spain)",
    "Georgian (Georgia)",
    "Gujarati (India)",
    "Croatian (Croatia)",
    "Zulu (South Africa)",
    "Icelandic (Iceland)",
    "Italian (Italy)",
    "Javanese (Indonesia)",
    "Kannada (India)",
    "Khmer (Cambodia)",
    "Lao (Laos)",
    "Latvian (Latvia)",
    "Lithuanian (Lithuania)",
    "Hungarian (Hungary)",
    "Malayalam (India)",
    "Marathi (India)",
    "Dutch (Netherlands)",
    "Nepali (Nepal)",
    "Norwegian Bokmål (Norway)",
    "Polish (Poland)",
    "Portuguese (Brazil)",
    "Portuguese (Portugal)",
    "Romanian (Romania)",
    "Sinhala (Sri Lanka)",
    "Slovak (Slovakia)",
    "Slovenian (Slovenia)",
    "Sundanese (Indonesia)",
    "Swahili (Tanzania)",
    "Swahili (Kenya)",
    "Finnish (Finland)",
    "Swedish (Sweden)",
    "Tamil (India)",
    "Tamil (Singapore)",
    "Tamil (Sri Lanka)",
    "Tamil (Malaysia)",
    "Telugu (India)",
    "Vietnamese (Vietnam)",
    "Turkish (Turkey)",
    "Urdu (Pakistan)",
    "Urdu (India)",
    "Greek (Greece)",
    "Bulgarian (Bulgaria)",
    "Russian (Russia)",
    "Serbian (Serbia)",
    "Ukrainian (Ukraine)",
    "Hebrew (Israel)",
    "Arabic (Saudi Arabia)",
    "Hindi (India)",
    "Thai (Thailand)",
    "Korean (South Korea)",
    "Mandarin (Traditional, Taiwan)",
    "Cantonese (Traditional, Hong Kong)",
    "Japanese (Japan)",
    "Mandarin (Simplified, China)"
  ];
  
  module.exports = {
    data,
    languages
  };