  let languages = [
    "Afrikaans (South Africa)",
    "Amharic (Ethiopia)",
    "Armenian (Armenia)",
    "Azerbaijani (Azerbaijan)",
    "Indonesian (Indonesia)",
    "Malay (Malaysia)",
    "Bengali (Bangladesh)",
    "Bengali (India)",
    "Catalan (Spain)",
    "Czech (Czech Republic)",
    "Danish (Denmark)",
    "German (Germany)",
    "English (United States)",
    "Spanish (Spain)",
    "Basque (Spain)",
    "Filipino (Philippines)",
    "French (France)",
    "Galician (Spain)",
    "Georgian (Georgia)",
    "Gujarati (India)",
    "Croatian (Croatia)",
    "Zulu (South Africa)",
    "Icelandic (Iceland)",
    "Italian (Italy)",
    "Javanese (Indonesia)",
    "Kannada (India)",
    "Khmer (Cambodia)",
    "Lao (Laos)",
    "Latvian (Latvia)",
    "Lithuanian (Lithuania)",
    "Hungarian (Hungary)",
    "Malayalam (India)",
    "Marathi (India)",
    "Dutch (Netherlands)",
    "Nepali (Nepal)",
    "Norwegian Bokmål (Norway)",
    "Polish (Poland)",
    "Portuguese (Brazil)",
    "Portuguese (Portugal)",
    "Romanian (Romania)",
    "Sinhala (Sri Lanka)",
    "Slovak (Slovakia)",
    "Slovenian (Slovenia)",
    "Sundanese (Indonesia)",
    "Swahili (Tanzania)",
    "Swahili (Kenya)",
    "Finnish (Finland)",
    "Swedish (Sweden)",
    "Tamil (India)",
    "Tamil (Singapore)",
    "Tamil (Sri Lanka)",
    "Tamil (Malaysia)",
    "Telugu (India)",
    "Vietnamese (Vietnam)",
    "Turkish (Turkey)",
    "Urdu (Pakistan)",
    "Urdu (India)",
    "Greek (Greece)",
    "Bulgarian (Bulgaria)",
    "Russian (Russia)",
    "Serbian (Serbia)",
    "Ukrainian (Ukraine)",
    "Hebrew (Israel)",
    "Arabic (Saudi Arabia)",
    "Hindi (India)",
    "Thai (Thailand)",
    "Korean (South Korea)",
    "Mandarin (Traditional, Taiwan)",
    "Cantonese (Traditional, Hong Kong)",
    "Japanese (Japan)",
    "Mandarin (Simplified, China)"
  ];

  module.exports = {
    languages
  };