branch-defaults:
  docker:
    environment: ButterflyEffect-env
environment-defaults:
  ButterflyEffect-env:
    branch: null
    repository: null
global:
  application_name: Butterfly Effect
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-east-2::platform/Docker running on
    64bit Amazon Linux/2.12.5
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
